In [13]:
import numpy as numpy
import pandas as pd

df_all = pd.read_csv('../processed_data/data.csv')

df_all

00:08:52:34:40:ec  00:23:aa:5a:d6:f8  00:23:aa:5a:d6:f9  \
0                    0                  0                  0   
1                    0                  0                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   
..                 ...                ...                ...   
145                  0                  0                 81   
146                  0                  0                 81   
147                  0                  0                 81   
148                  0                  0                 81   
149                  0                  0                 80   

     00:23:aa:69:3c:01  00:23:aa:69:3c:02  00:23:aa:b5:9b:9a  \
0                   50                 83                  0   
1                   53                 85                  0   
2                   57                 85                  0   
3                   53                 85                  0   
4                   62                 85                  0   
..                 ...                ...                ...   
145                 93                 99                  0   
146                 94                 99                  0   
147                 92                 99                  0   
148                 93                 99                  0   
149                 93                 99                  0   

     00:23:aa:b6:2d:aa  08:10:77:3f:68:71  08:5d:dd:1b:63:02  \
0                    0                 97                  0   
1                    0                 97                  0   
2                    0                 95                  0   
3                    0                 93                  0   
4                    0                 94                  0   
..                 ...                ...                ...   
145                  0                 78                  0   
146                  0                  0                  0   
147                  0                 78                  0   
148                  0                 80                  0   
149                  0                 75                  0   

     12:23:aa:5a:d6:f9  ...  88:3c:1c:da:ce:6e  8a:3c:1c:10:95:58  \
0                    0  ...                  0                  0   
1                    0  ...                  0                  0   
2                    0  ...                  0                  0   
3                    0  ...                  0                  0   
4                    0  ...                  0                  0   
..                 ...  ...                ...                ...   
145                  0  ...                  0                 40   
146                 81  ...                  0                  0   
147                 81  ...                  0                  0   
148                 81  ...                  0                  0   
149                 81  ...                  0                 46   

     b0:df:c1:53:87:a1  b4:a9:4f:1a:d4:3e  b4:a9:4f:70:ce:4c  \
0                    0                  0                  0   
1                    0                  0                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   
..                 ...                ...                ...   
145                  0                  0                  0   
146                  0                  0                  0   
147                  0                  0                  0   
148                  0                  0                  0   
149                  0                  0                  0   

     ba:3c:1c:65:2c:c6  ba:a9:4f:70:ce:4c  e4:be:ed:96:73:1b  \
0                    0              

In [14]:
x_train = df_all.iloc[:,:-1].values
y_train = df_all.iloc[:,-1].values

x_train

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0, 81, ..., 40,  0,  0],
       [ 0,  0, 81, ...,  0,  0,  0],
       [ 0,  0, 80, ..., 40,  0,  0]], dtype=int64)

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rnd_clf = RandomForestClassifier(n_estimators=100, max_leaf_nodes=4, n_jobs=-1, random_state=42)
rnd_clf.fit(x_train, y_train)

pred_train = rnd_clf.predict(x_train)
pred_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [16]:
df_test = pd.read_csv('../test/processed_data/data.csv')
df_test

00:08:52:34:40:ec  00:23:aa:5a:d6:f8  00:23:aa:5a:d6:f9  \
0                   0                  0                  0   
1                   0                  0                  0   
2                   0                  0                  0   
3                   0                  0                  0   
4                   0                  0                  0   
..                ...                ...                ...   
70                  0                  0                 80   
71                  0                  0                 72   
72                  0                  0                 70   
73                  0                  0                 67   
74                  0                  0                 67   

    00:23:aa:69:3c:01  00:23:aa:69:3c:02  00:23:aa:b5:9b:9a  \
0                   0                 84                  0   
1                   0                 83                  0   
2                  40                 83                  0   
3                   0                 83                  0   
4                   0                 83                  0   
..                ...                ...                ...   
70                 96                 99                  0   
71                 91                 99                  0   
72                 92                  0                  0   
73                 91                 99                  0   
74                 91                 99                  0   

    00:23:aa:b6:2d:aa  08:10:77:3f:68:71  08:5d:dd:1b:63:02  \
0                   0                 81                  0   
1                   0                 93                  0   
2                   0                 92                  0   
3                   0                 93                  0   
4                   0                 92                  0   
..                ...                ...                ...   
70                  0                 80                  0   
71                  0                 65                  0   
72                  0                 80                  0   
73                  0                 80                  0   
74                  0                 78                  0   

    12:23:aa:5a:d6:f9  ...  88:3c:1c:da:ce:6e  8a:3c:1c:10:95:58  \
0                   0  ...                  0                  0   
1                   0  ...                  0                  0   
2                   0  ...                  0                  0   
3                   0  ...                  0                  0   
4                   0  ...                  0                  0   
..                ...  ...                ...                ...   
70                 78  ...                  0                  0   
71                  0  ...                  0                  0   
72                 67  ...                  0                  0   
73                 72  ...                  0                  0   
74                 70  ...                  0                  0   

    b0:df:c1:53:87:a1  b4:a9:4f:1a:d4:3e  b4:a9:4f:70:ce:4c  \
0                   0                  0                  0   
1                   0                  0                  0   
2                   0                  0                  0   
3                   0                  0                  0   
4                   0                  0                  0   
..                ...                ...                ...   
70                  0                  0                 40   
71                  0                  0                  0   
72                  0                  0                  0   
73                  0                  0                  0   
74                  0                  0                  0   

    ba:3c:1c:65:2c:c6  ba:a9:4f:70:ce:4c  e4:be:ed:96:73:1b  \
0                   0                  0                  0   
1                   0            

In [17]:

x_test = df_test.iloc[:,:-1].values
y_test = df_test.iloc[:,-1].values

pred_test = rnd_clf.predict(x_test)
pred_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 2, 5, 2, 2, 2, 2, 3, 2, 2, 4, 2, 4, 4, 2, 2, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [18]:
print(accuracy_score(y_test, pred_test))

0.8266666666666667
