In [1]:
import numpy as numpy
import pandas as pd

df_all = pd.read_csv('../processed_data/data.csv')

df_all

00:03:c0:25:11:3e  00:08:52:34:40:e8  00:08:52:34:40:e9  \
0                    0                  0                  0   
1                    0                  0                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   
..                 ...                ...                ...   
370                  0                  0                  0   
371                  0                  0                  0   
372                  0                  0                  0   
373                  0                  0                  0   
374                  0                 40                 40   

     00:08:52:34:40:ec  00:08:52:5d:3b:ad  00:08:52:5d:3b:af  \
0                    0                  0                  0   
1                    0                  0                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   
..                 ...                ...                ...   
370                  0                  0                  0   
371                  0                  0                 57   
372                 40                  0                 57   
373                  0                 57                 60   
374                 40                 67                 60   

     00:0b:81:9b:d1:6e  00:23:aa:5a:d6:f8  00:23:aa:5a:d6:f9  \
0                    0                  0                  0   
1                    0                  0                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   
..                 ...                ...                ...   
370                  0                  0                 81   
371                  0                  0                 72   
372                  0                  0                 70   
373                  0                  0                 70   
374                  0                  0                 70   

     00:23:aa:69:3c:01  ...  88:3c:1c:da:ce:6e  8a:3c:1c:10:95:58  \
0                   50  ...                  0                  0   
1                   53  ...                  0                  0   
2                   57  ...                  0                  0   
3                   53  ...                  0                  0   
4                   62  ...                  0                  0   
..                 ...  ...                ...                ...   
370                 97  ...                  0                 53   
371                 93  ...                  0                  0   
372                 92  ...                 50                  0   
373                 92  ...                  0                  0   
374                 92  ...                 50                  0   

     b0:df:c1:53:87:a1  b4:a9:4f:1a:d4:3e  b4:a9:4f:70:ce:4c  \
0                    0                  0                  0   
1                    0                  0                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   
..                 ...                ...                ...   
370                  0                  0                  0   
371                  0                  0                  0   
372                  0                  0                  0   
373                  0                  0                  0   
374                  0                  0                 40   

     ba:3c:1c:65:2c:c6  ba:a9:4f:70:ce:4c  e4:be:ed:96:73:1b  \
0                    0              

In [2]:
from sklearn.model_selection import train_test_split

x = df_all.iloc[:,:-1].values
y = df_all.iloc[:,-1].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=None)

x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rnd_clf = RandomForestClassifier(n_estimators=100, max_leaf_nodes=10, n_jobs=-1, random_state=42)
rnd_clf.fit(x_train, y_train)

pred_train = rnd_clf.predict(x_train)
pred_train

array([3, 2, 2, 5, 1, 1, 4, 1, 2, 2, 5, 5, 4, 3, 2, 4, 1, 3, 4, 3, 4, 2,
       1, 3, 1, 3, 5, 5, 3, 2, 5, 5, 5, 5, 4, 4, 3, 5, 1, 5, 2, 3, 1, 5,
       2, 4, 2, 3, 1, 1, 3, 3, 4, 4, 2, 3, 3, 1, 2, 5, 1, 4, 4, 1, 3, 2,
       2, 3, 5, 4, 5, 2, 4, 4, 2, 5, 2, 1, 4, 2, 2, 4, 2, 5, 1, 1, 1, 2,
       2, 1, 5, 5, 4, 5, 2, 2, 3, 2, 5, 3, 5, 4, 4, 3, 5, 5, 4, 2, 1, 1,
       4, 3, 3, 2, 3, 4, 4, 2, 5, 5, 5, 5, 3, 4, 2, 3, 3, 3, 5, 1, 5, 2,
       3, 4, 1, 2, 4, 5, 5, 2, 1, 5, 1, 2, 5, 2, 3, 4, 2, 3, 5, 1, 5, 1,
       5, 2, 3, 1, 3, 1, 1, 1, 3, 2, 4, 4, 3, 4, 3, 2, 4, 1, 4, 4, 2, 4,
       3, 3, 2, 1, 2, 4, 3, 4, 5, 1, 4, 5, 2, 4, 5, 3, 3, 2, 3, 1, 1, 1,
       4, 3, 5, 1, 4, 4, 4, 3, 5, 2, 1, 2, 2, 1, 1, 1, 3, 1, 5, 5, 3, 4,
       5, 4, 3, 3, 4, 5, 4, 5, 5, 5, 4, 3, 3, 1, 3, 3, 5, 4, 2, 1, 1, 1,
       2, 3, 1, 4, 2, 1, 4, 4, 1, 5, 2, 4, 3, 5, 5, 2, 5, 5, 5, 4, 1, 1,
       3, 3, 5, 3, 3, 1, 1, 5, 4, 4, 1, 5, 3, 4, 3, 4, 5, 4, 5, 2, 2, 3,
       5, 2, 2, 5, 3, 2, 5, 1, 3, 1, 2, 4, 5, 2], d

In [4]:
print(accuracy_score(y_train, pred_train))

1.0


In [5]:
pred_test = rnd_clf.predict(x_test)
pred_test

array([3, 1, 1, 5, 1, 4, 2, 2, 4, 2, 4, 1, 4, 1, 4, 4, 1, 4, 5, 2, 1, 3,
       1, 4, 4, 2, 5, 3, 3, 5, 1, 2, 1, 5, 3, 2, 1, 1, 3, 3, 4, 4, 1, 3,
       2, 2, 2, 1, 1, 1, 4, 2, 4, 3, 3, 5, 2, 1, 3, 2, 2, 4, 2, 1, 5, 1,
       4, 3, 3, 2, 2, 3, 5, 5, 5], dtype=int64)

In [6]:
print(accuracy_score(y_test, pred_test))

1.0
